[package]
name = "urzua-io"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
thiserror = { workspace = true }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
